directories:
  - src
  - tests
  - docs
  - data

files:
  - README.md
  - requirements.txt
  - .gitignore
  - src/__init__.py
  - tests/__init__.py

placement_rules:
  py: src
  md: docs
  txt: root
  yaml: root
  json: data

modularity_guidelines:
  max_file_size: 1000  # lines
  max_complexity: 10   # McCabe complexity
  naming_convention: "snake_case"
  file_purpose_comment: true
