stages:
  - name: Project Initialization
    description: Set up the initial project structure and environment
    tasks:
      - Create project directory
      - Initialize git repository
      - Set up virtual environment
    priorities:
      - Create project directory
      - Initialize git repository
      - Set up virtual environment
    constraints:
      - name: project_directory_exists
        description: Ensure the project directory has been created
        condition: "'project_directory' in state and state['project_directory']"

  - name: Coding Conventions Setup
    description: Define and set up coding conventions for the project
    tasks:
      - Generate coding conventions file
      - Review and adjust conventions as needed
      - Integrate conventions with Aider
    priorities:
      - Generate coding conventions file
      - Review and adjust conventions as needed
      - Integrate conventions with Aider
    constraints:
      - name: conventions_file_exists
        description: Ensure the coding conventions file has been created
        condition: "'conventions_file' in state and state['conventions_file']"

  - name: Requirements Gathering
    description: Collect and document project requirements
    tasks:
      - Interview stakeholders
      - Document functional requirements
      - Document non-functional requirements
    priorities:
      - Interview stakeholders
      - Document functional requirements
      - Document non-functional requirements
    constraints:
      - name: stakeholders_interviewed
        description: Ensure stakeholders have been interviewed
        condition: "'stakeholders_interviewed' in state and state['stakeholders_interviewed']"
      - name: requirements_documented
        description: Ensure requirements have been documented
        condition: "'functional_requirements' in state and 'non_functional_requirements' in state"

  - name: Domain Modeling
    description: Create and refine the domain model
    tasks:
      - Identify key domain concepts
      - Define relationships between concepts
      - Create initial domain model diagram
    priorities:
      - Identify key domain concepts
      - Define relationships between concepts
      - Create initial domain model diagram
    constraints:
      - name: domain_concepts_identified
        description: Ensure key domain concepts have been identified
        condition: "'domain_concepts' in state and len(state['domain_concepts']) > 0"
      - name: domain_model_created
        description: Ensure the initial domain model diagram has been created
        condition: "'domain_model_diagram' in state and state['domain_model_diagram']"

transitions:
  - from: Project Initialization
    to: Requirements Gathering
    condition: All initial setup tasks completed

  - from: Requirements Gathering
    to: Coding Conventions Setup
    condition: Initial requirements gathered

  - from: Coding Conventions Setup
    to: Domain Modeling
    condition: Coding conventions defined and integrated

  - from: Project Initialization
    to: Coding Conventions Setup
    condition: All initial setup tasks completed

  - from: Requirements Gathering
    to: Domain Modeling
    condition: All requirements documented and approved

  - from: Domain Modeling
    to: Requirements Gathering
    condition: Need to refine requirements based on domain model
